package core

import (
	"context"
	"errors"
	"fmt"

	"github.com/nakamuraitsuki/Girder/infrastructure/ovn"
)

// ConnectSwitchToRouter connects an OVN logical switch to an OVN logical router.
//
// Naming convention (mirrors the switch-port-name = counterpart-name pattern
// used by ConnectNICtoSwitch), with Girder-specific prefixes to avoid name
// collisions that OVN itself does not prevent:
//   - Logical_Router_Port name = "to-" + switchName (the router's "view" of
//     the connection). The "to-" prefix avoids collisions with the switch's
//     own name -- e.g. Gateway switches are named after the gateway itself,
//     so without this prefix a router port could end up sharing its name
//     with the switch it connects to, which silently breaks ovn-northd's
//     chassisredirect ("cr-*") port generation for gateway router ports.
//   - Logical_Switch_Port name = routerName + "-to-" + switchName (the
//     switch's "view" of the connection). Logical_Switch_Port.name is
//     unique across the *entire* NB DB table (not scoped per switch), so a
//     plain routerName would collide as soon as the same router connects
//     to a second switch/gateway.
func (c *Core) ConnectSwitchToRouter(ctx context.Context, switchName, routerName string) error {
	sw, err := c.ovn.GetSwitch(ctx, switchName)
	if err != nil {
		return fmt.Errorf("failed to get switch %q: %w", switchName, err)
	}

	router, err := c.ovn.GetRouter(ctx, routerName)
	if err != nil {
		return fmt.Errorf("failed to get logical router %q: %w", routerName, err)
	}

	routerPortName := RouterPortName(switchName)

	// OVN: creates Logical_Router_Port on the router side.
	// MAC is auto-generated by CreateLogicalRouterPort when empty.
	// Networks (IP assignment) are handled by a separate operation
	// (out of scope for this connect operation).
	lrp, err := c.ovn.CreateLogicalRouterPort(ctx, router, &ovn.LogicalRouterPort{
		Name: routerPortName,
	})
	if err != nil {
		return fmt.Errorf("failed to create logical router port %q on router %q: %w", routerPortName, routerName, err)
	}

	// OVN: creates Logical_Switch_Port(type="router") on the switch side,
	// bound to the router port via options["router-port"].
	// Addresses is set to the special "router" keyword so OVN dynamically
	// resolves the MAC from the paired Logical_Router_Port, instead of
	// requiring Girder to keep a duplicate copy of the MAC in sync.
	switchPortName := LogicalSwitchPortName(routerName, switchName)
	if _, err := c.ovn.CreateLogicalSwitchPort(ctx, sw, &ovn.LogicalSwitchPort{
		Name:      switchPortName,
		Type:      "router",
		Addresses: []string{"router"},
		Options: map[string]string{
			"router-port": lrp.Name,
		},
	}); err != nil {
		if delErr := c.ovn.DeleteLogicalRouterPort(ctx, router, lrp.Name); delErr != nil {
			return fmt.Errorf("failed to create logical switch port %q on switch %q and failed to delete logical router port %q: %v, %v", switchPortName, switchName, lrp.Name, err, delErr)
		}
		return fmt.Errorf("failed to create switch-side port for router %q (logical router port %q rolled back): %w", routerName, lrp.Name, err)
	}

	return nil
}

// DisconnectSwitchFromRouter disconnects an OVN logical switch from an OVN logical router.
func (c *Core) DisconnectSwitchFromRouter(ctx context.Context, switchName, routerName string) error {
	sw, err := c.ovn.GetSwitch(ctx, switchName)
	if err != nil {
		return fmt.Errorf("failed to get switch %q: %w", switchName, err)
	}

	router, err := c.ovn.GetRouter(ctx, routerName)
	if err != nil {
		return fmt.Errorf("failed to get logical router %q: %w", routerName, err)
	}

	routerPortName := RouterPortName(switchName)

	if _, err := c.ovn.GetLogicalRouterPort(ctx, router, routerPortName); err != nil {
		if errors.Is(err, ovn.ErrLogicalRouterPortNotFound) {
			return fmt.Errorf("switch %q is not connected to router %q", switchName, routerName)
		}
		return fmt.Errorf("failed to get logical router port %q: %w", routerPortName, err)
	}

	// First, remove the switch-side port to avoid leaving a dangling
	// options["router-port"] reference if router port deletion fails.
	switchPortName := LogicalSwitchPortName(routerName, switchName)
	if err := c.ovn.DeleteLogicalSwitchPort(ctx, sw, switchPortName); err != nil {
		return fmt.Errorf("failed to delete logical switch port %q on switch %q: %w", switchPortName, switchName, err)
	}

	// Then, remove the router-side port.
	if err := c.ovn.DeleteLogicalRouterPort(ctx, router, routerPortName); err != nil {
		return fmt.Errorf("switch port removed but failed to delete logical router port %q (inconsistent state, manual check required): %w", routerPortName, err)
	}

	return nil
}